name: Run Example

on:
  pull_request:
    branches:
      - main  # The branch to which PRs are being made

jobs:
  test-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Install the python version needed, e.g., '3.8', '3.9', '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip  # Add other dependencies here if needed

    - name: Run script
      run: python examples/example.py  # Run the script